---
title: "Exercise 4"
author: "Carilli"
date: '`r format(lubridate::today(), "%B %d, %Y")`'
output: 
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    theme: flatly
    highlight: tango
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, message = FALSE,
                      warning = FALSE, error = FALSE,
                      options(digits = 3, scipen = 999))
library(tidyverse)
```

## Data

```{r data}
anscome <- 
here::here("data", "AnscombesQuartet.csv") %>% 
  read_csv()
```

## (a)

```{r}
anscombe %>% 
  summarytools::descr(stats = list("mean", "sd"))

anscombe %>% 
  summarize(across(everything(), list(mean = mean, variance = var))) %>% 
  pivot_longer(everything(),names_to = "measure", values_to = "value")
```

## (b)

```{r}
anscombe %>% 
  pivot_longer(everything(),
   names_to = c(".value", "set"),
   names_pattern = "(.)(.)"
 ) %>% 
  ggplot(aes(x = x, y = y, color = set)) + 
  geom_point() 
```

